# Generated by Django 5.2.5 on 2026-06-11 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0004_direccion'),
        ('Negocio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=20)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='pedidodetalle',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='ProductoOferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Negocio.oferta')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.producto')),
            ],
            options={
                'unique_together': {('producto', 'oferta')},
            },
        ),
        migrations.AddField(
            model_name='oferta',
            name='productos',
            field=models.ManyToManyField(blank=True, related_name='ofertas', through='Negocio.ProductoOferta', to='Cliente.producto'),
        ),
    ]
